config/routes.rb
Rails.application.routes.draw do
  get 'sends/index'

  get 'zams/index'
  scope '/categories' do
      get 'zams/index'
  end
    scope '/posts' do
      get 'zams/index'
  end
##поисковик
  get 'results/index'
##пароли
  devise_for :users
##обычные страницы
root 'posts#welcom'
resources :posts, only: [:show, :index, :welcom]
resources :categories, only: [:show]
    
##админка
 namespace :admin do
     resources :posts, except: [:show, :index, :welcom]
    resources :categories, except: [:show]   
 end

#теги
resources :tags, only: [:show]   

##вызов замерщика

    
end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :posts
     validates :name, presence: true
    has_ancestry
end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :category

  has_many :taggings, dependent: :destroy
    has_many :tags, through: :taggings

    mount_uploader :image, ImageUploader
    mount_uploader :image1, ImageUploader
    mount_uploader :image2, ImageUploader
    mount_uploader :image3, ImageUploader
    validates :title, :summary, :body, presence: true

include PgSearch
    pg_search_scope :search_everywhere, against: [:title, :body]
    paginates_per 4

    def all_tags
        self.tags.map(&:name).join(', ')
    end
    def all_tags=(names)
        self.tags = names.split(',').map do |name|
        Tag.where(name: name.strip).first_or_create
    end
    end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
        has_many :taggings
    has_many :posts, through: :taggings
    
    def self.counts
        self.select("name, count(taggings.tag_id) as count").joins(:taggings).group("name, taggings.tag_id")
    end
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :post
  belongs_to :tag
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable, :validatable
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
        before_action :authenticate_user!
        before_action :check_admin
    protected
    
    def check_admin
        redirect_to root_path, alert: "У вас нет прав доступа к данной странице" unless current_user.admin?
    end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::AdminController
    before_action :set_category, only: [ :edit, :update, :destroy ]
    
    def index
        @categories = Category.all
    end
    
    def new
        @category = Category.new
        @categories = Category.all.order(:name)
    end
    
    def create
        @category = Category.new(category_params)
        if @category.save
           redirect_to admin_categories_path, success: 'Категория успешно создана'
        else
            @categories = Category.all.order(:name)
            flash[:danger] = 'Категория не создана'
            render :new
        end
    end
    
    def edit
        @categories = Category.where("id != #{@category.id}").order(:name)
    end
    
    def update
        if @category.update_attributes(category_params)
            redirect_to admin_categories_path, success: 'Категория успешно обновлена'
        else
            @categories = Category.where("id != #{@category.id}").order(:name)
            flash[:danger] = 'Категория не обновлена'
            render :edit
        end
    end
    
    def destroy
        @category.destroy
        redirect_to admin_categories_path, success: 'Категория успешно удалена'
    end
    
    private
    
    def set_category
        @category = Category.find(params[:id])
    end
    
    def category_params
        params.require(:category).permit(:name, :parent_id)
    end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::AdminController
    before_action :set_post, only: [ :edit, :update, :destroy ]
    
    def new
        @post = Post.new(params[:post])
    end
    def create
        @post = Post.new(post_params)
        if @post.save
            redirect_to @post, success: 'Объект создан'
        else
            flash.now[:danger] = 'Объект не создан'
            render :new
        end
    end
    
    def edit
    end
    
    def update
        if @post.update_attributes(post_params)
            redirect_to @post, success: 'Объект обновлен'
        else
            flash.now[:danger] = 'Объект не обновлен'
            render :edit
        end
    end
    
    def destroy
        @post.destroy
        redirect_to posts_path, success: 'Объект удален'
    end
    
    private
    
    def set_post
        @post = Post.find(params[:id])
    end
    
    def post_params
        params.require(:post).permit(:title, :summary, :body, :image, :image1, :image2, :image3, :category_id, :all_tags)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
add_flash_types :success, :danger, :info, :warning
    
     def set_title
        session[:name] = "King Kitchen"
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :set_category, only: :show

    def show
        @posts = Post.where("category_id = #{params[:id]}").page params[:page]
    end
    
    private
    
    def set_category
        @category = Category.find(params[:id])
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :set_post, only: :show
    before_action :set_title, only: [:welcom, :index]
    
    def welcom
    end
    
    def index
#        @posts = Post.paginate(page: params[:page], per_page: 6)
        @posts = Post.all.page params[:page]
    end
    
    def show
        session[:name] = @post.title
    end
    
    private
    
    def set_post
        @post = Post.find(params[:id])
    end
   
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  def index
      @search = Post.search_everywhere(params[:v1])
  end
end

app/controllers/sends_controller.rb
class SendsController < ApplicationController
  def index
      @clue = params[:email]
      ZamsMailer.sending(@clue).deliver
      redirect_to root_path, success: 'Подписка оформлена!'
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
    def show
        @tag = Tag.find_by(name: params[:id])
        @posts = @tag.posts
    end
end

app/controllers/zams_controller.rb
class ZamsController < ApplicationController
  def index
      @clue = params[:name] + "." + params[:city] + "." + params[:phone1] + "." + params[:email]
      ZamsMailer.zayavka(@clue).deliver
      redirect_to root_path, success: 'Запрос успешно отправлен!'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
 def bootstrap_class_for(name)
      { success: "alert-success",
        error: "alert-danger",
        danger: "alert-danger",
        alert: "alert-warning",
        notice: "alert-info"
      }[name.to_sym] || name
    end
end

app/helpers/posts_helper.rb
module PostsHelper
    def tag_cloud(tags, classes)
        max = tags.sort_by(&:count).last
        tags.each do |tag|
        index = tag.count.to_f / max.count * (classes.size)
            yield(tag, classes[index.round])
    end
    end
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/sends_helper.rb
module SendsHelper
end

app/helpers/zams_helper.rb
module ZamsHelper
end

app/views/admin/categories/_form.html.erb
    <div class="mid2">
<% if @category.errors.any? %>
<div class="alert alert-danger mar2">
    <h5><%= t('common.errors') %></h5>
    <ul>
        <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
</div>
<% end %>
    </div>

<%= form_for [:admin, @category] do |f| %>
<div class="form-group">
<%= f.label :name %>
<%= f.text_field :name, class: 'form-control' %>
</div>

<div class="form-group">
<%= f.label :parent_id %>
<%= f.collection_select :parent_id, @categories, :id, :name, { include_blank: true }, class: 'form-control' %>
</div>

<div class="form-group">
<%= f.submit 'Сохранить', class: 'btn btn-primary wd' %>
<%= link_to 'Назад', :back, class: 'btn btn-outline-secondary wd' %>
</div>
<% end %>

app/views/admin/categories/edit.html.erb
<div class="mid2 clearfix">
<h2 class="post__zag">Редактирование</h2>

<%= render 'form' %>
</div>

app/views/admin/categories/index.html.erb
<div class="mid2">
<h2 class="post__zag">Категории</h2>
<div class="buttons_panel">
    <%= link_to 'Новая категория', new_admin_category_path, class: 'btn btn-outline-primary btn-sm mar' %>
</div>
</div>
<section id="categories">
    <div class="mid">
<table class="table">
    <thead>
        <tr>
            <th>№</th>
            <th>Название</th>
            <th>Категория родитель</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <% @categories.each_with_index do |category, index| %>
            <tr>
                <td><%= index + 1 %></td>
                <td><%= category.name %></td>
                <td><%= category.parent.name if category.parent.present? %></td>
                <td>
                    <%= link_to 'Изменить', edit_admin_category_path(category), class: 'btn btn-outline-primary btn-sm' %>
                    <%= link_to 'Удалить', admin_category_path(category), method: :delete, data: { confirm: 'Вы уверены?'}, class: 'btn btn-outline-danger btn-sm' %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>
    </div>
</section>

app/views/admin/categories/new.html.erb
<div class="mid2 clearfix">
<h2 class="post__zag">Новая категория</h2>
<%= render 'form' %>
</div>

app/views/admin/posts/_form.html.erb
<% if @post.errors.any? %>
<div class="alert alert-danger">
    <h5><%= t('common.errors') %></h5>
    <ul>
        <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
</div>
<% end %>

<%= form_for [:admin, @post], html: { multipart: true } do |f| %>
<div class="form-group">
<%= f.label :title %>
<%= f.text_field :title, class: 'form-control' %>
</div>

<div class="form-group">
<%= f.label :summary %>
<%= f.text_area :summary, class: 'form-control' %>
</div>

<div class="form-group">
<%= f.label :body %>
<%= f.trix_editor :body, class: 'editor' %>
</div>

<div class="form-group">
<%= f.label :Теги %>
<%= f.text_field :all_tags, class: 'form-control' %>
</div>


<div class="form-group">
<%= f.file_field :image %>
</div>

<div class="form-group">
<%= f.file_field :image1 %>
</div>

<div class="form-group">
<%= f.file_field :image2 %>
</div>

<div class="form-group">
<%= f.file_field :image3 %>
</div>

<div class="form-group">
    <%= f.label :Категории %>
<!--<%= f.label :category_id %> -->
<%= f.collection_select :category_id, Category.order(:name), :id, :name, { include_blank: true }, class: 'form-control' %>
</div>

<div class="form-group">
<%= f.submit 'Сохранить', class: 'btn btn-primary wd' %>
<%= link_to 'Назад', :back, class: 'btn btn-outline-secondary wd' %>
</div>
<% end %>

app/views/admin/posts/edit.html.erb
<div class="mid2 clearfix">
<h2 class="post__zag">Редактирование</h2>

<%= render 'form' %>
</div>

app/views/admin/posts/new.html.erb
<div class="mid2 clearfix">
<h2 class="post__zag">Новый объект</h2>
<%= render 'form' %>
</div>

app/views/categories/show.html.erb
<div class="mid2 clearfix">
    <div class="tag__style">
        <% tag_cloud(Tag.counts, %w{tag1, tag2, tag3, tag4}) do |tag, css_class| %>
        <%= link_to tag.name, tag_path(tag.name), class: 'css_class no__link tag__a' %>
        <% end %>   
    </div>
<div class="zagolovok">
<h1 class="items__text"><%= @category.name %></h1>
</div>    
    <% session[:name] = @category.name %>
 

<section id="posts">
<%= render @posts %>
</section>

<!--Вывод кухон после пагинации-->
<div class="kit_pag">
      <%= paginate @posts, window: 2 %>
</div>
  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= session[:name] %></title>
  <%= stylesheet_link_tag    'application', 'https://fonts.googleapis.com/css?family=Roboto:300,400&amp;subset=cyrillic', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    <meta http-equiv="X-UA-Compatible" content="IE-edge">
    <meta name="viewport" content="width=device-width, initial-scale=0.6, maximum-scale=0.6">
</head>
<body>
<!--Хедер с меню и др инормацией-->
        <header style="header__top">
       <div class="main__block__header crownfon">
            <div class="mid clearfix">
<!--
                  <div id="case__float" class="logo">
                     <img src="images/logo.png" class="logo__img" alt="Логотип">
                  </div>
-->                 <div class="red__logo left">
                <%= link_to image_tag("red__logo.png", :class => 'red__logo_tr'), root_path %>
                    </div>
                 <a href="#modal"> <div class="zamer__main__block left">
                      <div class="zamer__text">Вызвать замерщика</div>
                      <div class="zamer__img">
                          <%= image_tag('GMOKAT.png', :alt => "logo", :class => 'img__zamer') %>
                          </div>
                     </div></a>
                  <div class="kontacts right">
                      <p class="kontacts__info ">т. 89196174444</p>
                      <p class="kontacts__info ">т. 89871449292</p>
                          <p class="kontacts__info mail "><a href="mailto:freezkos@yandex.ru" class="no__link" target="_blank">freezkos@yandex.ru</a></p>
                  </div>
              </div>
         </div>
      </header>   
<!--    Меню -->
    <%= render 'shared/submenu' %>
<!--    поисковик--> 
      <div class="search__block">
          <div class="mid">
              <div class="search__mid">
<!--
              <form action="" method="post" id="search-block-form" class="wow bounceIn">
              <div class="form-item">
                <input type="text" name="" value="" size="15" maxlength="128" placeholder="Найти...">
              </div>
              <div class="form-actions">
                <input type="submit" id="edit-submit" name="op" value="Поиск" class="form-submit">
              </div>
              </form>

-->
    <%= form_tag("/results/index", :method => "get") do %>
                <div class="search__blog"> 
    <%= text_field_tag(:v1, nil, placeholder: "Введите текст...") %>
    <%= submit_tag "Искать", class:'wd btnS right' %>
                </div>
    <% end %>
              </div>
          </div>
      </div>
    
    <div class="fon__ad">
        <div class="mid2">
        <% if user_signed_in? %>
              <%= link_to "Выход", destroy_user_session_path, method: :delete, class: "fInlB pad" %>
            <% if user_signed_in? && current_user.admin? %>
            <%= link_to 'Новый объект', new_admin_post_path, class: 'new__obj__add' %> 
            <% end %>
            <% else %>
            <div class="inlB">
              <%= link_to "Вход", new_user_session_path, class: "fInlB" %>
               <%= link_to "Регистрация", new_user_registration_path, class: "fInlB" %>
            </div>  
            <% end %>
    </div>
    </div>
<!--    Главный блок с отображением всего остального-->
  
    <section class="crownfon clearfix">
<div class="mid2 clearfix">
    <div class="row">
        <div class="col-md-12">
            <% flash.each do |name, message| %>
            <div class="alert <%= bootstrap_class_for(name) %> mar2">
                <button class="close" data-dismiss="alert">&times;</button>
                <%= message %>
            </div>
            <% end %>
        </div>
    </div>
    </div>
        <%= yield %>
</section>
<!--    Футер и информация об авторе
     <footer class="crownfon">
                <div class="f__fon animate bounceInUp">
                <div class="mid">
                    <hr class="line__menu">
                    <ul class="menu__ul__f">
                    <li class="menu__f"><a class="menu__a__f" href="#">Кухни</a>
                        <ul class="vl__li">
                                <li class="vl"><a class="menu__a__vl" href="#">Модерн</a></li>
                                <li class="vl"><a class="menu__a__vl" href="#">Классические</a></li>
                        </ul>
                    </li>
					<li class="menu__f"><a class="menu__a__f" href="#">Шкафы</a>
                                <ul class="vl__li">
                                 <li class="vl"><a class="menu__a__vl" href="#">Шкафы-купе</a></li> 
                                </ul>
                    </li>
					<li class="menu__f"><a class="menu__a__f" href="#">Детские</a>
                                     <ul class="vl__li">
                                 <li class="vl"><a class="menu__a__vl" href="#">Кровати</a></li>
                                <li class="vl"><a class="menu__a__vl" href="#">Шкафы-купе</a></li>
                                    </ul>
                        
                        </li>
					<li class="menu__f"><a class="menu__a__f" href="#">Прихожки</a>
                                     <ul class="vl__li">
                                 <li class="vl"><a class="menu__a__vl" href="#">Шкафы-купе</a></li>
                                    </ul>
                    </li>
                    <li class="menu__f"><a class="menu__a__f" href="#">Офисы</a>
                                     <ul class="vl__li">
                                 <li class="vl"><a class="menu__a__vl" href="#">Шкафы-купе</a></li>
                                <li class="vl"><a class="menu__a__vl" href="#">Стеллажи</a></li>
                                    </ul>
                        </li>
					<li class="menu__f"><a class="menu__a__f" href="#">Спальни</a>
                        
                                     <ul class="vl__li">
                                 <li class="vl"><a class="menu__a__vl" href="#">Шкафы-купе</a></li>
                                <li class="vl"><a class="menu__a__vl" href="#">Кровати</a></li>
                        </ul>
                        </li>  
                    </ul>    
                </div>
                </div>

                <div class="author">
                    <div class="mid clearfix">
                    <span class="author__name left wow bounceInUp">2017©FreezkoS</span>
                        <div class="vk__logo right  wow bounceInUp"><span class="vk__text">Мы Вконтакте </span>
                            <%= image_tag('vk.png', :alt => "logo", :class => 'img__vk') %>
                            </div>
                    </div>
                </div>
            </footer>
-->
    
     <%= render 'shared/subfooter' %>
    
    
				<script src="js.js"></script>
      
			<!--	<script src="js.js"></script>-->
<!--Якорь возврата	-->
      <div id="toTop">
           <%= image_tag('yakor.png', :alt => "logo", :class => 'img__w') %>
      </div>
<!--Телефоны-->
       <div id="phone">
            <%= image_tag('phone.png', :alt => "logo", :class => 'img__w') %>
      </div>
      
      <div class="number__block">
                      <p class="t__text">т. 89196174444</p>
                      <p class="t__text">т. 89871449292</p>
                      <a href="mailto:freezkos@yandex.ru" target="_blank" class="no__link">
                          <p class="em__text">freezkos@yandex.ru</p>
                      </a>
      </div>
      
      <!--Модальное окно 1-->
    <% if user_signed_in? %>
     <div class="remodal" data-remodal-id="modal">
      <button data-remodal-action="close" class="remodal-close"></button>
         <h1 class="zamer__zag">Вызов замерщика</h1>
         <div class="zamer__info left">
            <div class="zamer__info__text">
                <p class="info__modal__text">
                Одно из главных достоинств мебели, изготовленной на заказ, – возможность её «встраивания» в углы, ниши, между полом и потолком и пр. Естественно, при заказе такой мебели необходимо произвести идеально точные замеры помещения. Во избежание ошибок и неточностей замер всегда производится специалистами компании.
                </p>
                <p class="info__modal__text">
                С учётом Ваших пожеланий и особенностей помещения дизайнер разрабатывает первый, предварительный эскиз мебельной композиции.
                </p>
             </div>
             <div class="zamer__info__img">
                 <%= image_tag('big_bike.png', :alt => "logo", :class => 'img__zamer__auto') %>
             </div>
         </div>
         
        <div class="forma__modal right">
<!--
  <form>

        <label>Ваше Имя</label>
        <input name="name" placeholder="Введите Имя...">

        <label>Ваш город</label>
        <input name="email" type="email" placeholder="Уфа">

        <label>Контактный телефон</label>
         <input name="email" type="email" placeholder="Введите номер...">
        
         <label>Email</label>
         <input name="email" type="email" placeholder="Введите email...">
        
        <input id="submit" name="submit" type="submit" value="Отправить">

    </form>
-->

              
      <%= form_tag("zams/index", :method => "get") do %>
            <label class="first">Ваше Имя</label>
            <%= text_field_tag(:name, nil, required: true, placeholder: "Введите имя...") %>
            <label>Ваш город</label>
            <%= text_field_tag(:city, nil, required: true, placeholder: "Введите город...") %>
            <label>Контактный телефон</label>
            <%= text_field_tag(:phone1, nil, required: true, placeholder: "Введите телефон...") %>
            <label>Email</label>
            <%= email_field_tag(:email, nil, required: true, placeholder: "Введите почту...") %>
            <%= submit_tag "Отправить", class: 'button' %>
    <% end %>
            
        </div>
    </div>
    <% else %>
    <div class="remodal wow zoomIn" data-remodal-id="modal">
        <button data-remodal-action="close" class="remodal-close"></button>
        <h2 class="items__text__2">Вам необходимо авторизоваться!</h2>
    </div>
    <% end %>
</body>
</html>

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>

/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
/*
var disqus_config = function () {
this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};
*/
(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://king-kitchen.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
                            

app/views/posts/_post.html.erb
<arctical class="post clearfix no__link">
    <%= link_to(post_path(post), class: "no__link") do %>
    <div class="mid2 cleardix">
    <%= image_tag post.image.url(:thumb), class: 'thumb myimg' if post.image? %>
    <small>
        <% if user_signed_in? && current_user.admin? %>
        <time>
        <span class="no__link__2">
        <%= post.created_at.to_date.strftime("%d.%m.%Y") %>
        </span>
        |
        <%= link_to 'Ред', edit_admin_post_path(post), class: "no__link" %>
        |
        <%= link_to 'Уд', admin_post_path(post), class: "no__link", method: :delete, data: { confirm: 'Вы уверены?' } %>
        </time>
        <% end %>
    </small>
    <section>  
    <h2 class="t1"><%= link_to post.title, post_path(post), class: "no__link" %></h2>
    <h2 class="t2"><%= post.summary %></h2>
    </section>
        
     </div>
    <% end %>
</arctical>

app/views/posts/index.html.erb
<div class="mid2 margin">
    <% if user_signed_in? && current_user.admin? %>
<%= link_to 'Новый объект', new_admin_post_path, class: 'btn btn-outline-primary pull-xxs-right' %>   
    <% end %>
</div>
<div class="mid clearfix">
    <div class="zagolovok"> 
<h1 class="items__text">Вся мебель</h1>
    </div>
<!--Вывод кухон-->
<%= render @posts %>
<!--Вывод кухон после пагинации-->
<div class="kit_pag">
<%= paginate @posts, window: 1 %>
</div>
</div>

app/views/posts/new.html.erb
<div class="mid2 clearfix">
<h2 class="post__zag mar2">Новый объект</h2>
<%= render 'form' %>
</div>

app/views/posts/show.html.erb
<arctical class="post2 clearfix">
    <div class="mid2 clearfix">
        
        <div class="tag__style">
        <% tag_cloud(Tag.counts, %w{tag1, tag2, tag3, tag4}) do |tag, css_class| %>
        <%= link_to tag.name, tag_path(tag.name), class: 'css_class no__link tag__a' %>
        <% end %>   
    </div>
        
    <div class="zagolovok">  
    <h1 class="items__text"><%= @post.title %></h1>
    </div>
         
    <small>
        <time>
        <% if @post.category.present? %>
        <%= link_to @post.category.name, @post.category, class: "no__link" %>
        |
        <% end %>
        <%= @post.created_at.to_date.strftime("%d.%m.%Y") %>
        <% if user_signed_in? && current_user.admin? %>
        |
        <%= link_to 'Ред', edit_admin_post_path(@post), class: "no__link" %>
        |
        <%= link_to 'Уд', admin_post_path(@post), class: "no__link", method: :delete, data: { confirm: 'Вы уверены?' } %>
        <% end %>
        </time>
    </small>
        
                    <!--Gallery-->
            <div id="gallery" style="display:none;">
        <%= image_tag @post.image.url(:large), data: { image: @post.image.url(:large) } %>
        <%= image_tag @post.image1.url(:large), data: { image: @post.image1.url(:large) } %>
        <%= image_tag @post.image2.url(:large), data: { image: @post.image2.url(:large) } %>
        <%= image_tag @post.image3.url(:large), data: { image: @post.image3.url(:large) } %>
            </div>
                    <a href="#modal" class="no__link">
                    <div class="zamer__block__gallery">
                    Вызвать замерщика
                    </div>
                    </a>
    <section class="post-body">        
<!--  <%= image_tag @post.image.url(:large), class: 'img-show' if @post.image? %>-->
        <p class="t3">Описание</p>
    <%= @post.body.html_safe %><br>
        <h5><%= @post.summary %></h5>
    </section>
        
               <div class="tablo__zakaza">
                        <h1 class="tablo__zag">Внимание!</h1>
                        <div class="tablo__text">
                            Для того, чтобы произвеcти заказ выбранного Вами товара, необходимо обязательно <span class="war">Вызвать замерщика</span> или связаться с нами любим из доступных способов, а именно по электронной почте или моб. телефону, которые указанны в начале стр <span class="war">(если Вы используете полную версию сайта)</span>, либо по нажатию кнопки в правом нижнем углу <span class="war">(если используется моб. версия сайта)</span>.
                        </div>
                    </div>
    </div>
</arctical>
<div class="mid2 clearfix">
    <p class="t3">Комментарии</p>
<%= render 'disqus' %>
</div>

app/views/sends/index.html.erb
<h1>Sends#index</h1>
<p>Find me in app/views/sends/index.html.erb</p>

app/views/shared/_submenu_categories.html.erb
<!--
<ul class="nav nav-pills nav-stacked nested_nav">
    <% categories.each do |category, children| %>
        <li>
     <%= link_to category.name, category, class: "nav-link #{'active' if current_page? (category_path(category))}" %>
        <%= render 'shared/submenu_categories', categories: children if children.present? %> 
    </li>
    <% end %>
</ul>
-->

app/views/tags/show.html.erb
<div class="mid2 clearfix">    
<div class="tag__style">
        <% tag_cloud(Tag.counts, %w{tag1, tag2, tag3, tag4}) do |tag, css_class| %>
        <%= link_to tag.name, tag_path(tag.name), class: 'css_class no__link tag__a' %>
        <% end %>   
    </div>
    <div class="zagolovok">
<h1 class="items__text"><%= @tag.name %></h1>
</div>  
<% if @tag.posts.empty? %>
    <h2>Мебели под этим тегом нет в каталоге</h2>
<% else %>
<%= render @tag.posts %>
<%end%>

</div>

app/views/zams/index.html.erb
<h1>Zams#index</h1>
<p>Find me in app/views/zams/index.html.erb</p>